// Journal de log et de contrôle : erreurs, requêtes lentes, actions importantes des joueurs et de l'admin.
// Les évènements sont gardés en mémoire puis écrits par lots (un seul aller-retour vers Supabase) : le journal ne ralentit jamais une requête.
const buf = [];
let lastFlush = 0, ready = false;
export const RETENTION_DAYS = 14;

/** niveau : 'info' (action) | 'warn' (refus, lenteur) | 'error' (plantage, base injoignable) ; kind : action, refus, lent, erreur, base, cron, admin… */
export function logEvent({ level = 'info', kind = 'action', user = null, route = '', status = 0, ms = 0, detail = '' }) {
  buf.push({ ts: Date.now(), level, kind, usr: user, route, status, ms: Math.round(ms), detail: String(detail ?? '').slice(0, 400) });
  if (buf.length > 300) buf.shift();
}

async function ensure(env) {
  if (ready) return;
  await env.DB.batch([
    env.DB.prepare('CREATE TABLE IF NOT EXISTS logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ts BIGINT NOT NULL, level TEXT NOT NULL, kind TEXT NOT NULL, usr TEXT, route TEXT NOT NULL DEFAULT \'\', status INTEGER NOT NULL DEFAULT 0, ms INTEGER NOT NULL DEFAULT 0, detail TEXT NOT NULL DEFAULT \'\')'),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS logs_ts ON logs(ts DESC)'),
    env.DB.prepare('ALTER TABLE logs ENABLE ROW LEVEL SECURITY'),
  ]);
  ready = true;
}

/** Écrit le journal en attente (au plus toutes les 8 s, ou dès 8 évènements). `env` = la base NON comptée (le journal ne fausse pas les statistiques). */
export async function flushLogs(env, force = false) {
  if (!buf.length) return;
  if (!force && buf.length < 8 && Date.now() - lastFlush < 8000) return;
  lastFlush = Date.now();
  const items = buf.splice(0);
  try {
    await ensure(env);
    await env.DB.batch(items.map(e => env.DB.prepare('INSERT INTO logs (ts, level, kind, usr, route, status, ms, detail) VALUES (?,?,?,?,?,?,?,?)').bind(e.ts, e.level, e.kind, e.usr, e.route, e.status, e.ms, e.detail)));
  } catch (e) { console.error('flushLogs', e); }
}

/** Lecture pour l'admin : filtres par niveau / type, recherche libre, pagination par identifiant. */
export async function readLogs(env, { level = '', kind = '', q = '', before = 0, limit = 100 } = {}) {
  await ensure(env);
  const where = [], args = [];
  if (level) { where.push('level = ?'); args.push(level); }
  if (kind) { where.push('kind = ?'); args.push(kind); }
  if (q) { where.push("(coalesce(usr, '') ILIKE ? OR route ILIKE ? OR detail ILIKE ?)"); const s = `%${q.replace(/[\\%_]/g, '')}%`; args.push(s, s, s); }
  if (before) { where.push('id < ?'); args.push(before); }
  const rows = (await env.DB.prepare(`SELECT id, ts, level, kind, usr, route, status, ms, detail FROM logs ${where.length ? 'WHERE ' + where.join(' AND ') : ''} ORDER BY id DESC LIMIT ${Math.min(300, Math.max(1, limit))}`).bind(...args).all()).results;
  const counts = (await env.DB.prepare('SELECT level, count(*)::int n FROM logs WHERE ts > ? GROUP BY level').bind(Date.now() - 86400000).all()).results;
  return { logs: rows, last24h: Object.fromEntries(counts.map(c => [c.level, c.n])) };
}

/** Purge : on garde 14 jours de journal. */
export async function pruneLogs(env) {
  await ensure(env);
  await env.DB.prepare('DELETE FROM logs WHERE ts < ?').bind(Date.now() - RETENTION_DAYS * 86400000).run();
}
