-- Schéma Supabase (PostgreSQL). Les cartes ne sont enregistrées qu'au moment où elles sont tirées ;
-- le catalogue complet (titres, rangs) est servi en fichiers statiques (public/catalog).
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  salt TEXT NOT NULL,
  hash TEXT NOT NULL,
  coins BIGINT NOT NULL DEFAULT 200,
  pack_stock BIGINT NOT NULL DEFAULT 10,
  test_mode BIGINT NOT NULL DEFAULT 0,
  packs_opened BIGINT NOT NULL DEFAULT 0,
  is_bot BIGINT NOT NULL DEFAULT 0,      -- joueurs simulés qui animent le marché
  is_admin BIGINT NOT NULL DEFAULT 0,    -- menu d'administration
  showcase TEXT,                          -- vitrine : JSON des (au plus 3) cartes exposées sur le profil
  drop_w TEXT,                            -- taux de drop personnalisés (JSON par rareté), réglés par l'admin
  pack_ts BIGINT NOT NULL,
  duel_wins BIGINT NOT NULL DEFAULT 0,
  duel_losses BIGINT NOT NULL DEFAULT 0,
  created BIGINT NOT NULL,
  friend_code TEXT UNIQUE            -- code secret contenu dans le QR code
);
CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  created BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS cards (
  id BIGINT PRIMARY KEY,
  title TEXT NOT NULL,
  extract TEXT NOT NULL DEFAULT '',
  image TEXT,
  url TEXT NOT NULL DEFAULT '',
  views BIGINT NOT NULL DEFAULT 0,
  rarity TEXT NOT NULL,
  atk BIGINT NOT NULL DEFAULT 0,
  def BIGINT NOT NULL DEFAULT 0,
  shiny BIGINT NOT NULL DEFAULT 0,
  enriched BIGINT NOT NULL DEFAULT 0   -- 0 rien, 1 Wikipédia lu, 2 terminé (image cherchée sur Wikipédia puis Wikidata)
);
CREATE INDEX IF NOT EXISTS cards_title ON cards(lower(title) text_pattern_ops);
CREATE UNIQUE INDEX IF NOT EXISTS users_name ON users(lower(name));
CREATE TABLE IF NOT EXISTS inventory (
  user_id BIGINT NOT NULL REFERENCES users(id),
  card_id BIGINT NOT NULL REFERENCES cards(id),
  qty BIGINT NOT NULL,
  acquired BIGINT,                   -- date de la dernière obtention (tri par date)
  rar BIGINT NOT NULL DEFAULT 0,     -- copies des champs de tri de la carte : la collection se pagine sans relire la table cards
  sh BIGINT NOT NULL DEFAULT 0,
  skey BIGINT NOT NULL DEFAULT 0,    -- rang de rareté * 1e9 + popularité
  nk TEXT NOT NULL DEFAULT '',        -- titre en minuscules
  fav BIGINT NOT NULL DEFAULT 0,
  lvl BIGINT NOT NULL DEFAULT 0,      -- niveau de fusion
  PRIMARY KEY (user_id, card_id)
);
CREATE TABLE IF NOT EXISTS auctions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id BIGINT NOT NULL REFERENCES users(id),
  card_id BIGINT NOT NULL REFERENCES cards(id),
  start_price BIGINT NOT NULL,
  bid BIGINT NOT NULL DEFAULT 0,
  bidder_id BIGINT REFERENCES users(id),
  ends_at BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open'
);
CREATE INDEX IF NOT EXISTS auctions_open ON auctions(status, ends_at);
CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id BIGINT NOT NULL REFERENCES cards(id),
  price BIGINT NOT NULL,
  ts BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS sales_card ON sales(card_id, id);
CREATE TABLE IF NOT EXISTS trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_id BIGINT NOT NULL REFERENCES users(id),
  to_id BIGINT NOT NULL REFERENCES users(id),
  offer_card BIGINT NOT NULL REFERENCES cards(id),
  want_card BIGINT NOT NULL REFERENCES cards(id),
  status TEXT NOT NULL DEFAULT 'pending',
  created BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS hits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  title TEXT NOT NULL,
  shiny BIGINT NOT NULL DEFAULT 0,
  ts BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS friends (
  user_id BIGINT NOT NULL REFERENCES users(id),
  friend_id BIGINT NOT NULL REFERENCES users(id),
  created BIGINT NOT NULL,
  seen BIGINT NOT NULL DEFAULT 1,      -- 0 = nouvel ami que ce joueur n'a pas encore vu (pastille rouge)
  PRIMARY KEY (user_id, friend_id)
);
CREATE TABLE IF NOT EXISTS friend_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_id BIGINT NOT NULL REFERENCES users(id),
  to_id BIGINT NOT NULL REFERENCES users(id),
  status TEXT NOT NULL DEFAULT 'pending',
  created BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS friend_requests_to ON friend_requests(to_id, status);
CREATE TABLE IF NOT EXISTS bids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auction_id BIGINT NOT NULL REFERENCES auctions(id),
  user_id BIGINT NOT NULL REFERENCES users(id),
  amount BIGINT NOT NULL,
  ts BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS bids_auction ON bids(auction_id);
CREATE TABLE IF NOT EXISTS achievements (
  user_id BIGINT NOT NULL REFERENCES users(id),
  key TEXT NOT NULL,
  ts BIGINT NOT NULL,
  PRIMARY KEY (user_id, key)
);
CREATE TABLE IF NOT EXISTS reserve (        -- cartes déjà complétées (texte + photo) tirées d'avance : les paquets s'ouvrent sans attente
  id BIGINT PRIMARY KEY,
  rarity TEXT NOT NULL,
  rank BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS reserve_rarity ON reserve(rarity);
CREATE TABLE IF NOT EXISTS prepared (        -- paquets tirés et complétés d'avance pour un joueur (non encore ouverts)
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  cards TEXT NOT NULL,
  ts BIGINT NOT NULL,
  w TEXT NOT NULL DEFAULT ''           -- taux de drop utilisés (users.drop_w) : un paquet préparé avec d'autres taux est jeté
);
CREATE INDEX IF NOT EXISTS prepared_user ON prepared(user_id, id);
CREATE TABLE IF NOT EXISTS wanted (          -- cartes cherchées par un joueur : un joueur simulé les met en vente à l'heure indiquée
  card_id BIGINT PRIMARY KEY,
  at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS wanted_at ON wanted(at);
CREATE TABLE IF NOT EXISTS quizzes (         -- questions d'un article écrites par le modèle de langage (une seule génération par article)
  card_id BIGINT PRIMARY KEY,
  questions TEXT NOT NULL,
  model TEXT NOT NULL,
  ts BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS favorites (       -- cartes marquées d'une étoile
  user_id BIGINT NOT NULL,
  card_id BIGINT NOT NULL,
  ts BIGINT NOT NULL,
  PRIMARY KEY (user_id, card_id)
);

CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);   -- clés VAPID des notifications, etc.
CREATE TABLE IF NOT EXISTS push_subs (        -- appareils abonnés aux notifications (un joueur peut en avoir plusieurs)
  endpoint TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  ts BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS push_subs_user ON push_subs(user_id);
CREATE TABLE IF NOT EXISTS push_msgs (        -- notifications en attente de lecture par le service worker
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  endpoint TEXT NOT NULL,                       -- appareil destinataire
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  tag TEXT,
  ts BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS push_msgs_ep ON push_msgs(endpoint);
CREATE INDEX IF NOT EXISTS inventory_skey ON inventory(user_id, skey, card_id);
CREATE INDEX IF NOT EXISTS inventory_acq ON inventory(user_id, acquired, card_id);
CREATE INDEX IF NOT EXISTS inventory_nk ON inventory(user_id, nk, card_id);
CREATE INDEX IF NOT EXISTS inventory_fav ON inventory(user_id, fav, skey, card_id);

CREATE TABLE IF NOT EXISTS fight_events (     -- journal des combats (début, pauses, reprises, fin, erreurs) : sert à comprendre pourquoi un combat s'arrête
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts BIGINT NOT NULL,
  battle TEXT NOT NULL,
  players TEXT NOT NULL,
  kind TEXT NOT NULL,
  detail TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS fight_events_ts ON fight_events(ts);

CREATE TABLE IF NOT EXISTS usage (            -- lignes lues par type de requête et par jour (statistiques internes)
  day TEXT NOT NULL,
  sig TEXT NOT NULL,
  n BIGINT NOT NULL DEFAULT 0,
  rows BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (day, sig)
);

CREATE INDEX IF NOT EXISTS bids_user ON bids(user_id, auction_id);

-- messagerie privée : une ligne par message (a < b = les deux joueurs), et un résumé par joueur et par conversation (liste, non lus)
CREATE TABLE IF NOT EXISTS dms (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, a BIGINT NOT NULL, b BIGINT NOT NULL, from_id BIGINT NOT NULL, body TEXT NOT NULL, ts BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS dms_conv ON dms(a, b, id);
CREATE TABLE IF NOT EXISTS convs (user_id BIGINT NOT NULL, peer_id BIGINT NOT NULL, last_ts BIGINT NOT NULL, last_body TEXT NOT NULL, last_mine BIGINT NOT NULL DEFAULT 0, unread BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (user_id, peer_id));

-- Journal de log et de contrôle (erreurs, requêtes lentes, actions) : conservé 14 jours (purge par la tâche planifiée). L'application le crée aussi toute seule au besoin.
CREATE TABLE IF NOT EXISTS logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ts BIGINT NOT NULL, level TEXT NOT NULL, kind TEXT NOT NULL, usr TEXT, route TEXT NOT NULL DEFAULT '', status INTEGER NOT NULL DEFAULT 0, ms INTEGER NOT NULL DEFAULT 0, detail TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS logs_ts ON logs(ts DESC);

-- Sécurité : aucune table n'est lisible par les clés publiques (le Worker utilise la clé service_role, qui contourne ce verrou).
-- récompense quotidienne, quêtes, quiz du jour (aussi créés à la demande par le Worker)
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_day TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_streak INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS quests (user_id BIGINT NOT NULL, day TEXT NOT NULL, qid TEXT NOT NULL, progress INTEGER NOT NULL DEFAULT 0, claimed INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (user_id, day, qid));
CREATE TABLE IF NOT EXISTS daily_quiz (day TEXT PRIMARY KEY, title TEXT NOT NULL, extract TEXT NOT NULL DEFAULT '', questions TEXT NOT NULL, model TEXT, created BIGINT NOT NULL, winner BIGINT, awarded BIGINT);
CREATE TABLE IF NOT EXISTS daily_quiz_runs (user_id BIGINT NOT NULL, day TEXT NOT NULL, started BIGINT NOT NULL, answers TEXT, correct INTEGER, delta INTEGER, finished BIGINT, PRIMARY KEY (user_id, day));

CREATE TABLE IF NOT EXISTS tournaments (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, creator BIGINT NOT NULL, stake BIGINT NOT NULL, maxp INTEGER NOT NULL DEFAULT 4, status TEXT NOT NULL DEFAULT 'open', stage TEXT, bracket TEXT, created BIGINT NOT NULL, started BIGINT, ended BIGINT);
CREATE TABLE IF NOT EXISTS tournament_players (tid BIGINT NOT NULL, user_id BIGINT NOT NULL, joined BIGINT NOT NULL, payout BIGINT, PRIMARY KEY (tid, user_id));

CREATE INDEX IF NOT EXISTS inventory_lvl ON inventory(user_id, lvl DESC, skey DESC, card_id DESC);

ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_v BIGINT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS title TEXT;
CREATE TABLE IF NOT EXISTS avatars (user_id BIGINT PRIMARY KEY, data TEXT NOT NULL, ts BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS user_titles (user_id BIGINT NOT NULL, tid TEXT NOT NULL, ts BIGINT NOT NULL, PRIMARY KEY (user_id, tid));

CREATE TABLE IF NOT EXISTS login_fails (k TEXT PRIMARY KEY, n INTEGER NOT NULL, first BIGINT NOT NULL);

DO $$ DECLARE t record; BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t.tablename);
  END LOOP;
END $$;
-- Fonction q() : le Worker envoie un lot de requêtes SQL (déjà paramétrées), exécuté dans UNE transaction.
-- Renvoie, pour chaque requête : { results: [lignes en JSON], changes: nombre de lignes touchées }.
-- Réservée à la clé « service_role » (celle du Worker) : jamais accessible depuis un navigateur.
CREATE OR REPLACE FUNCTION public.q(stmts jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  out jsonb := '[]'::jsonb; s jsonb; sql text; res jsonb; n bigint;
BEGIN
  FOR s IN SELECT value FROM jsonb_array_elements(stmts) LOOP
    sql := s->>'sql';
    IF sql ~* '^\s*(select|with|values)\M' THEN
      EXECUTE 'SELECT coalesce(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM (' || sql || ') t' INTO res;
      n := jsonb_array_length(res);
    ELSIF sql ~* '\mreturning\M' THEN
      EXECUTE 'WITH t AS (' || sql || ') SELECT coalesce(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM t' INTO res;
      n := jsonb_array_length(res);
    ELSE
      EXECUTE sql; GET DIAGNOSTICS n = ROW_COUNT; res := '[]'::jsonb;
    END IF;
    out := out || jsonb_build_array(jsonb_build_object('results', res, 'changes', n));
  END LOOP;
  RETURN out;
END $$;
REVOKE ALL ON FUNCTION public.q(jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.q(jsonb) TO service_role;
