ALTER TABLE users ADD COLUMN packs_opened INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS achievements (
  user_id INTEGER NOT NULL REFERENCES users(id),
  key TEXT NOT NULL,
  ts INTEGER NOT NULL,
  PRIMARY KEY (user_id, key)
);
