CREATE TABLE IF NOT EXISTS fight_events (id INTEGER PRIMARY KEY AUTOINCREMENT, ts INTEGER NOT NULL, battle TEXT NOT NULL, players TEXT NOT NULL, kind TEXT NOT NULL, detail TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS fight_events_ts ON fight_events(ts);
