ALTER TABLE users ADD COLUMN is_bot INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS reserve (id INTEGER PRIMARY KEY, rarity TEXT NOT NULL, rank INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS reserve_rarity ON reserve(rarity);
